import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const hanken = Hanken_Grotesk({
  variable: "--font-hanken-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const ztBros = localFont({
  src: "../font/ZTBrosOskon90s-Regular.otf",
  variable: "--font-zt-bros",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${hanken.variable} ${ztBros.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
